name: portfolio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: 'SpaceMono'
      fonts:
        - asset: assets/fonts/space-mono.ttf
        - asset: assets/fonts/space-mono-bold.ttf
          weight: 700

  assets:
    - assets/fonts/